language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer update --dev
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
  - pyrus install pear/PHP_CodeSniffer
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install phpmd/PHP_PMD
  - phpenv rehash

script:
  - pwd
  - phpunit --configuration phpunit.travis.xml
  #phpcs -p --standard=build/phpcs/Joomla --report=summary --report-file=build/checkstyle.txt --ignore="/*tmpl/*" src cli
  #phpcs -p --standard=build/phpcs/Joomla --report=emacs --report-file=build/checkstyle.txt --ignore="/*tmpl/*" src cli
  - phpcs -pvv --standard=build/phpcs/Joomla --report=summary --report-file=build/checkstyle.txt --ignore=/*tmpl/* /home/travis/build/jtester/jissues/cli
  - ant -v
  - cat build/checkstyle.txt
